### ISSUE TITLE
Comfy's banlist API link is outdated

### ISSUE THREAD

**Issue by vadcx** [Distortions81/Factorio-Community-List#4]
#2 link currently in repo no longer works: <https://getcomfy.eu/api/v1/ban/get/all> empty body 404

@Gerkiz ?

**Comment by Distortions81** [comment]
For the moment I changed the URL to the ban html and set it to scrape.
Also updated scraper in https://github.com/M45-Science/FactBanSync

**Comment by Gerkiz** [comment]
Sorry. The new url is:
[here](https://getcomfy.eu/api/v1/bans)

The reason for changing it was to make it more REST-like.
